version: "3.8"

services:
  db:
    image: mysql:8.2
    container_name: db-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: local
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample_test
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-mysql:/var/lib/mysql

volumes:
  db-mysql:
    name: db-mysql
